### ISSUE TITLE
How to apply babel loader?

### ISSUE THREAD

**Issue by LookRain** [sveltejs/svelte-loader#108]
I am working on a project with majority of users coming from developing countries, so I have to support transpiling to ES5.

I can't find any documentation on how to set up webpack configurations (yes i'm using the sapper webpack template) to support old browsers, so here I am asking for some help. Thanks in advance!

**Comment by kaisermann** [comment]
You have to make sure to run `babel-loader` after `svelte-loader` and to not ignore `node_modules/svelte` in your `babel-loader` configuration.


Something like this would work, but you would run babel over every dependency. You can also create `include` or `exclude` rules to help you with that, but it's important to not ignore any svelte dependency.

```js
module: {
    rules: [{
        test: /\.(htmlx?|svelte)$/,
        use: [{ /* babel-loader config */, /* svelte-loader config */],
    }]
}
```

Example of a `include` regexp which includes `src` and every `node_modules/svelte-*` directory: `src|node_modules[\\/]svelte-?`

**Comment by benwinding** [comment]
Does anyone have an example on how to do this?

**Comment by kaisermann** [comment]
@benwinding @LookRain I've forked the `sveltejs/template-webpack` and added the babel transpilation. I forgot to say on my comment above that you still have to transpile all the `js` helpers from svelte. 

https://github.com/kaisermann/template-webpack

This repo contains: 

- babel transpilation with automatic polyfills by using `@babel/preset-env`. You can check the `babel.config.js` file to exclude some unnecessary polyfills if needed.
- splitted chunks for the webpack runtime, libs (node_modules files) and polyfills

I'm not sure if the 'include: [/svelte/]' rule for js transpilation will cover all cases, but you get the point 😬

**Comment by benwinding** [comment]
@kaisermann Thanks so much for sharing that! Will hopefully be a great starting point :smiley:

**Comment by benwinding** [comment]
@kaisermann I can't get the demo to work though, is there anything I'm missing?....

1. `npx degit sveltejs/template-webpack test-svelte-app1`
2. `cd test-svelte-app1`
3. `yarn`
4. `yarn dev`
5. browse to [localhost:8080](http://localhost:8080)

The browser complains with the following message:
![Selection_041](https://user-images.githubusercontent.com/11782590/65234328-84c6e680-db13-11e9-9aab-e31758c924ed.png)

Can you confirm that the template works?

**Comment by theshem** [comment]
I ended up with the following in order to have ES5-compatible code with Webpack:

```js
// ...
rules: [
  // transpile js svelte helpers
  {
    test: /\.m?js$/,
    include: [/svelte/],
    use: ['babel-loader'],
  },
  {
    test: /\.(html|svelte)$/,
    exclude: /node_modules/,
    use: [
      'babel-loader',
      {
        loader: 'svelte-loader',
        options: {
          hotReload: true,
          emitCss: true,
        },
      },
    ],
  },
  // ...
]
```
Also polyfills are added through `@babel/preset-env`:

```js
[
  "@babel/preset-env",
  {
    "modules": false,
    "corejs": 3,
    "useBuiltIns": "usage",
    "targets": {
      "browsers": [
        "> 0.5%",
        "last 2 major versions",
        "safari >= 9",
        "not ie <= 11",
        "not dead"
      ]
    }
  }
]
```

However, to me, the bundle size is an issue here. I built a simple app (2-3 small components) and the bundle size was about 13KB. After looking through the bundle file, I noticed the use of `Set`, `Map`, `class`, `Reflect` (I don't know why it does what it does), ..., So I added Babel and core-js polyfills and it became 4.5X larger (59KB).

The idea behind Svelte is awesome, but the bundle size--which is known as pros of Svelte over the other options--might be an issue if you need it to be small.

**Comment by yazonnile** [comment]
created template for svelte+babel+webpack https://github.com/yazonnile/svelte-webpack-babel

**Comment by dloreto** [comment]
> created template for svelte+babel+webpack https://github.com/yazonnile/svelte-webpack-babel

![image](https://user-images.githubusercontent.com/29567012/96050977-e1154a80-0e7a-11eb-8177-7adcc7d39458.png)

**Comment by dummdidumm** [comment]
Thanks! Closing since this indeed doesn't seem active anymore and some potential solutions have been posted already.
