### ISSUE TITLE
(dev:true) is necessary for Svelte Devtools

### ISSUE THREAD

**Issue by frantic0** [sveltejs/svelte-loader#112]
#appologies, I hit comment accidentally 

I have been trying to use the extension Svelte Devtools. I found out that in order to have the extension connect successfully you do have to use 'dev:true' on the webpack config file to be able to inspect it. 

Perhaps it would be useful to set this by default? 

Best,
FØ

**Comment by pngwn** [comment]
Please add more detail.

**Comment by frantic0** [comment]
There is an error when it loads though. Just posted it here: https://github.com/RedHatter/svelte-devtools/issues/18
