### ISSUE TITLE
Hot reloading not working

### ISSUE THREAD

**Issue by tniyer2** [sveltejs/svelte-loader#113]
I am using svelte-loader with Webpack and getting the error below when I set hotReload to true. I also tried this with svelte/template-webpack and got the same result so I know it's not my configuration. The only thing I changed was adding the --hot option for webpack-dev-server.

TypeError: this.proxyTarget is undefined vendors~main.js line 208 > eval:63:7
proxyComponent proxy.js:56
    <anonymous> index.js:10
    js main.js:80
    __webpack_require__ runtime.js:786
    fn runtime.js:151
    1 main.js:137
    __webpack_require__ runtime.js:786
    checkDeferredModules runtime.js:46
    webpackJsonpCallback runtime.js:33
    <anonymous> main.js:1

**Comment by linvain** [comment]
Same here:

![image](https://user-images.githubusercontent.com/42490556/72689045-386dd080-3b1e-11ea-9122-d77ec7223ac5.png)

**Comment by linvain** [comment]
Seems like this lib isn't maintained

**Comment by j3rem1e** [comment]
Why is this issue closed ? HMR doesn't work and AFAIK this lib is the "official" webpack loader.

**Comment by rixo** [comment]
> Why is this issue closed ?

The OP closed it themselves, here's why...

Now, indeed, there is some significant lagging on maintenance of the official `svelte-loader` and `template-webpack` currently... But some members of the community have been organizing to catch up with all the pending issues & PR in Svelte repos lately, so there is hope that things will get sorted out eventually. Even if, let's face it, Webpack or HMR don't seem to have the highest priority.

Meanwhile, you can check out my [svelte-loader-hot](https://github.com/rixo/svelte-loader-hot) for HMR, and [svelte-template-webpack-hot](https://github.com/rixo/svelte-template-webpack-hot).

I am less generally overwhelmed than Svelte core team, so you can expect faster response time if you have some issues. And, if all goes according to plans, they should get merged in their official counterparts eventually, even if that's still a long shot. So using them for now and helping me iron out existing issues is probably a good way to help development of Svelte HMR and Webpack support.
