### ISSUE TITLE
Module not found: Error: Can't resolve 'svelte-loader' in 'C:\Users\PC MC\Desktop\svelte-native-template-master\app'  @ ./app.ts 

### ISSUE THREAD

**Issue by dina06** [sveltejs/svelte-loader#116]
hi, i want to start a new project with svelte native but i have this problem:
when i tried to execute this line-command : tns preview --bundle the qr code appear and i scan it and this is the result: 
Preparing project...
File change detected. Starting incremental webpack compilation...
Starting type checking service...
Using 1 worker with 4096MB memory limit

webpack is watching the files…

Hash: e7d699d773cd5473651e
Version: webpack 4.27.1
Time: 1174ms
Built at: 2019-12-24 3:09:27 PM
 3 assets
Entrypoint bundle = runtime.js vendor.js bundle.js
[./ sync ^\.\/app\.(css|scss|less|sass)$] . sync nonrecursive ^\.\/app\.(css|scss|less|sass)$ 174 bytes {bundle} [built]
[./ sync recursive (?<!\bApp_Resources\b.*)(?<!\.\/\btests\b\/.*?)\.(xml|css|js|(?<!\.d\.)ts|(?<!\b_[\w-]*\.)scss)$] . sync (?<!\bApp_Resources\b.*)(?<!\.\/\btests\b\/.*?)\.(xml|css|js|(?<!\.d\.)ts|(?<!\b_[\w-]*\.)scss)$ 187 bytes {bundle} [built]
[./app.css] 1.39 KiB {bundle} [optional] [built]
[./app.ts] 2.14 KiB {bundle} [built]
[tns-core-modules/application] external "tns-core-modules/application" 42 bytes {bundle} [built]
[tns-core-modules/bundle-entry-points] external "tns-core-modules/bundle-entry-points" 42 bytes {bundle} [built]
[tns-core-modules/data/observable-array/observable-array] external "tns-core-modules/data/observable-array/observable-array" 42 bytes {bundle} [built]
[tns-core-modules/file-system] external "tns-core-modules/file-system" 42 bytes {bundle} [built]
[tns-core-modules/text/formatted-string] external "tns-core-modules/text/formatted-string" 42 bytes {bundle} [built]
[tns-core-modules/text/span] external "tns-core-modules/text/span" 42 bytes {bundle} [built]
[tns-core-modules/trace] external "tns-core-modules/trace" 42 bytes {bundle} [built]
[tns-core-modules/ui/action-bar] external "tns-core-modules/ui/action-bar" 42 bytes {bundle} [built]
[tns-core-modules/ui/activity-indicator] external "tns-core-modules/ui/activity-indicator" 42 bytes {bundle} [built]
[tns-core-modules/ui/frame] external "tns-core-modules/ui/frame" 42 bytes {bundle} [built]
[tns-core-modules/ui/frame/activity] external "tns-core-modules/ui/frame/activity" 42 bytes {bundle} [built]
    + 47 hidden modules

with this is error
ERROR in ./app.ts
Module not found: Error: Can't resolve 'svelte-loader' in 'C:\Users\PC MC\Desktop\svelte-native-template-master\app'
 @ ./app.ts 51:0-31 52:13-16
have someone any idea to resolve it?
thank you

**Comment by fibric** [comment]
How did you create the project?

Do you find `svelte-loader` in your `package.json`? Im my `package.json` I find `"svelte-loader-hot": "github:halfnelson/svelte-loader#native"`.

And in my `webpack.config.js` I changed:
```
test: /\.svelte$/,
          exclude: /node_modules/,
          use: [
            {
              loader: 'svelte-loader',
```

to

```
test: /\.svelte$/,
          exclude: /node_modules/,
          use: [
            {
              loader: 'svelte-loader-hot',
```

**Comment by dina06** [comment]
yes  i found in package.json "
svelte-loader":"github:halfnelson/svelte-loader#native" and not
svelte-loader-hot   i can edit it or not??
thank you for your response

Le ven. 27 déc. 2019 à 21:46, Denny Trebbin <notifications@github.com> a
écrit :

**Comment by dina06** [comment]
so i have edited on the package.json and webpack.config.js and i have this
error


C:\Users\PC MC\mémoire fin d'étude\svelte-native-template-master>tns
preview --bundle
npm ERR! code ENOENT
npm ERR! syscall spawn git
npm ERR! path git
npm ERR! errno ENOENT
npm ERR! enoent Error while executing:
npm ERR! enoent undefined ls-remote -h -t ssh://
git@github.com/halfnelson/svelte-loader.git
npm ERR! enoent
npm ERR! enoent
npm ERR! enoent spawn git ENOENT
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! A complete log of this run can be found in:
npm ERR!
C:\tmp\nodejs\npm-cache\_logs\2019-12-28T19_06_17_181Z-debug.log
Command npm.cmd failed with exit code 1

**Comment by rixo** [comment]
It seems like you can't git SSH remotes, or maybe you don't have git at all on your machine?

Anyway, I've just merged and released the changes from @halfnelson, so you don't need to use the fork anymore (for which you need git). You can simply:

```bash
npm install --dev svelte-loader-hot@latest
```

Be sure to run `npm install` in the project dir too.

I think this issue doesn't really relate to svelte-loader though, it'd rather belong to [svelte-native-template](https://github.com/halfnelson/svelte-native-template/issues).

**Comment by dina06** [comment]
yes i think this issue belong to svelte-native-template because i had run this line-command npm install --dev svelte-loader-hot@latest and the problem of svelte-loader is fixed but i had an other problem whitch is:
[./App.svelte] 570 bytes {bundle} [built] [failed] [1 error]

ERROR in ./App.svelte 90:69
Module parse failed: Unexpected token (90:69)
You may need an appropriate loader to handle this file type.
|       }
| }
> import * as ___SVELTE_HMR_HOT_API from 'C:/Users/PC MC/mémoire fin d'étude/svelte-native-template-master/node_modules/svelte-loader-hot/lib/svelte3/hot-api.js'; import ___SVELTE_HMR_HOT_API_PROXY_ADAPTER from 'C:/Users/PC MC/mémoire fin d'étude/svelte-native-template-master/node_modules/svelte-loader-hot/node_modules/svelte-hmr/runtime/svelte-native/proxy-adapter-native.js';
| export default App
|   = module && module.hot
 @ ./app.ts 51:0-31 52:13-16
