### ISSUE TITLE
How can I set Svelte compiler options

### ISSUE THREAD

**Issue by gvmohzibat** [sveltejs/svelte-loader#122]
Hi,

There are some options in [Svelte compiler API page](https://svelte.dev/docs#Compile_time) which I can't find any documentation about them in svelte-loader.

How can I set Svelte compiler options like `immutable`, `legacy`, `accessors`? Should I use `svelte.config.js` file?

**Comment by NickolasBoyer** [comment]
You can just use them in the `options` field, see #76
