### ISSUE TITLE
`parseQuery` is renamed to `getOptions` in loader-utils 0.2.17 and up

### ISSUE THREAD

**Issue by settinghead** [sveltejs/svelte-loader#13]
This is causing `svelte-loader` to break because the current dependency is set at `^0.2.16` which implies new `npm install` will install the updated version of `loader-utils`.

**Comment by constgen** [comment]
Its definitely a reasonable fix. But I want to propose it also with changes in the **package.json**: upgraded version of 'svelte-loader' and 'loader-utils' dependency. #16
