### ISSUE TITLE
Optional chaining doesn't work

### ISSUE THREAD

**Issue by zamanruhy** [sveltejs/svelte-loader#137]
Optional chaining doesn't work with webpack and it most likely related to svelte-loader, as it works with rollup. Svelte itself already supports optional chaining since acorn has shipped it (see [repl](https://svelte.dev/repl/9c2bcfd4739a43388145812d637dbd9a?version=3.28.0)). But in webpack I am getting the next error:

![](http://joxi.ru/n2Ya4ZKubQn1l2.jpg)

Will the issue be fixed?

**Comment by Conduitry** [comment]
We'd need a repro for this. My guess is that you're either accidentally using an older version of Svelte or this is an error from a different plugin/loader that doesn't support this syntax.

**Comment by rabidpug** [comment]
Webpack 4 doesn’t support optional chaining as it uses an old version of acorn, see https://github.com/webpack/webpack/issues/10227#issuecomment-642734920 
Will be fixed in Webpack 5.

**Comment by fsevenm** [comment]
If you're using Svelte + Webpack 4 and want to use nullish coaslescing operator or optional chaining, you can use `resolutions` for now, I guess. 
Just add it to your top level package.json file,
```json
"resolutions": {
    "acorn": "8.0.1"
},
```
Then, run `yarn install`.

I've tested using null coalescing operator, no more errors, but I've not tested optional chaining yet.

See this issue for further information, there's also npm way, 
https://github.com/webpack/webpack/issues/10227#issuecomment-698662228

**Comment by N-NeelPatel** [comment]
Facing this problem while using optional chaining and coalescing operator in storybook svelte. 
![image](https://user-images.githubusercontent.com/29038590/200496195-4dbe7ba3-9cf7-4339-b9d4-b34412fe04b8.png)
