### ISSUE TITLE
Error: Module parse failed: Unexpected token

### ISSUE THREAD

**Issue by vaheqelyan** [sveltejs/svelte-loader#143]
I used this template https://github.com/sveltejs/template-webpack provided by svelte
After installing [svelte-grid](https://github.com/vaheqelyan/svelte-grid) webpack logs error
![image](https://user-images.githubusercontent.com/14107127/100379567-8bfa5600-302e-11eb-8a68-f455619f056c.png)

![image](https://user-images.githubusercontent.com/14107127/100379279-0c6c8700-302e-11eb-8ba7-d7e4f4618089.png)
don't know what could be wrong with this line

https://github.com/vaheqelyan/svelte-grid/blob/master/src/index.svelte#L107

REPO https://github.com/vaheqelyan/svelte-grid-webpack-template

**Comment by dimfeld** [comment]
You’ll need to set up Babel through babel-loader I think, or use Webpack 5. IIRC Webpack 4 doesn’t support the ?. syntax.

**Comment by evdama** [comment]
Right, I'm using rollup, same thing... blows up on https://github.com/vaheqelyan/svelte-grid/blob/03554d9ae30bfa2279699ba7f850b39d71098ffb/src/utils/other.js#L13

**Comment by vaheqelyan** [comment]
did so, unfortunately..
![image](https://user-images.githubusercontent.com/14107127/100446923-1394a300-30c9-11eb-8d66-5f027802edcc.png)
https://github.com/sveltejs/svelte-loader/issues/137#issuecomment-706750871 solving the issue for me

**Comment by vaheqelyan** [comment]
closing this. the error is not related to `svelte-loader`
