### ISSUE TITLE
Demos in /example are outdated

### ISSUE THREAD

**Issue by Smittyvb** [sveltejs/svelte-loader#165]
The examples in `/example` are using `1.0.0`. They should be updated to the current release.

**Comment by non25** [comment]
I think it is better to just delete them and make https://github.com/sveltejs/template-webpack a good place to start instead.
I was thinking about making branches with examples for different usecases.
css frameworks, babel, etc.
So users could see what are the steps to do something in particular.

**Comment by kyrylkov** [comment]
@Smittyvb @non25 Is this the only issue preventing v3 from getting released?

**Comment by Smittyvb** [comment]
@kyrylkov This issue can wait until 3.0.0 is released, and probably should in case there are any more last minute changes.

**Comment by kyrylkov** [comment]
@Smittyvb So what are the current blockers for v3 release?

**Comment by Smittyvb** [comment]
@kyrylkov Potentially #164, but it appears it would be fine to release without it. So nothing.

**Comment by kyrylkov** [comment]
@Smittyvb I see, OK.  The reason I'm asking is that we've been successfully using `master` branch in production, but it would be better to revert to regular npm versioning.

**Comment by Smittyvb** [comment]
@Conduitry given that you published the last version to NPM, could you tag+publish this? (make sure to remove `(unreleased)` from `CHANGELOG.md`)
