### ISSUE TITLE
@import of css from svelte component in node_modules

### ISSUE THREAD

**Issue by TheRealThor** [sveltejs/svelte-loader#167]
I am using module (filepond-svelte) that imports css itself from another node_module (filepond) with the directive

`<style global>
@import '/filepond/dist/filepond.min.css';
</style>`

When I am using hot reload development option, this is being added to the DOM

```
<style id="svelte-1x6jndj-style">
@import '/filepond/dist/filepond.min.css';
</style>
```

This import cannot be reached by the browser (404), since it is served from 'public' and not from 'node_modules'.
How can I configure svelte-loader to inline the content of the css file that is should be imported?

**Comment by non25** [comment]
Install `postcss`, `postcss-import`, `postcss-load-config`.

Configure `svelte-preprocess`:

```javascript
...
              preprocess: sveltePreprocess({
                postcss: true
              }),
...
```

Create `postcss.config.js`:

```javascript
module.exports = {
  plugins: [
    require('postcss-import')
  ]
}
```

**Comment by non25** [comment]
@TheRealThor did that help ?

**Comment by TheRealThor** [comment]
@non25  Hey, yes that did work. I actually played with  postcss-import before but I must have made a mistake. Thanks for you help!
