### ISSUE TITLE
Recompile stops after error in imported SCSS file

### ISSUE THREAD

**Issue by SpicyRicecaker** [sveltejs/svelte-loader#168]
I have the following code below, using the default `sveltejs/template-webpack` template
```svelte
<style lang="scss">
  @use 'styles';
</style>
```
When editing the `styles.scss` file, reloads are triggered on change just fine, until a mistake is made inside the scss file. 
After the webpack compilation error, editing the `styles.scss` file no longer causes any changes, and direct edits must be made to the `.svelte` file to trigger further reloads.

This issue only happens on webpack, presumably with the svelte loader, rollup handles changes to the scss file after an error just fine...

I think it's similar to #72 in a way, except only after compilation error

**Comment by non25** [comment]
@SpicyRicecaker Reproduced and fixed the issue.
In a meantime you can use staging branch of mine which contains this fix:

```sh
yarn add -D svelte-loader@non25/svelte-loader#staging
# or
npm i -D non25/svelte-loader#staging
```
