### ISSUE TITLE
Always use `shared: true` and `format: 'es'`

### ISSUE THREAD

**Issue by Rich-Harris** [sveltejs/svelte-loader#17]
There's no reason for `shared: true` to be configurable — there's no advantage in a webpack context to *not* sharing helpers.

I *think* the format should always be `es` — webpack can handle modules natively, right? (Not a webpack user, I could be wrong about this.) There's no reason for it to be anything else, is there?

More generally, rather than passing down each option in turn, it would probably make sense to pass through *all* the options, overriding the ones we need to.

**Comment by TheLarkInn** [comment]
Yup, so returned source can be esm export
