### ISSUE TITLE
Source maps include preprocessed source instead of original

### ISSUE THREAD

**Issue by rtpt-jonaslieb** [sveltejs/svelte-loader#171]
**Describe the bug**
I am using Svelte, TypeScript and Webpack. As far as I understand the source map feature implemented in sveltejs/svelte#5584, Svelte should transform the source map generated by TypeScript (via svelte-preprocess) into the final source map. This is not the case, apparently the source map contains the preprocessed JavaScript output. For example, the following Svelte component:

```
<script lang="ts">
  let name: string = 'world';

  console.log("This is App.svelte, line 4!");
</script>

<main>
  Hello {name}!
</main>
```

results in the following content in the sourcemap:

```
<script lang="ts">let name = 'world';
console.log("This is App.svelte, line 4!");
</script>

<main>
  Hello {name}!
</main>
```

**Logs**
The log line in the developer console reads `This is App.svelte, line 4! [...] App.svelte:2:8`.

**To Reproduce**
Clone this repository: https://github.com/baileyherbert/svelte-webpack-starter
Update to the latest Svelte version (`npm update`) and run the server `npm run dev`. View the source content in the browser console.

**Expected behavior**
I would expect the original TypeScript source to be contained in the source map. The line/col mappings should refer to the original locations in `App.svelte`.

**Information about your Svelte project:**
- Firefox 78.8.0esr
- Debian Linux 10
- Svelte version 3.35.0
- svelte-preprocess 4.6.9
- svelte-loader 3.0.0
- TypeScript 4.2.3
- Webpack 5.26.2

**Severity**
Severity: Only annoying.

**Comment by benmccann** [comment]
Thanks! Yes, I missed Webpack in the original description. I've transferred this to the `svelte-loader` repo because I think you're right that the support added to `rollup-plugin-svelte` was never added to `svelte-loader`

**Comment by non25** [comment]
@rtpt-jonaslieb Can you test a fix and tell me if that worked out for you?

```sh
yarn add -D svelte-loader@non25/svelte-loader#staging
# or
npm i -D non25/svelte-loader#staging
```

**Comment by rtpt-jonaslieb** [comment]
@non25 Sorry, I just got around to thoroughly test the new feature. 
The line mapping seems to be correct now. 

There is a regression however: Previously, the preprocessed `sourcesContent` was included in the source map, now the source map does not include any `sourcesContent` for Svelte files (or rather: the corresponding entry in `sourcesContent` is `null`).
It appears that the issue can be fixed by setting 

    js.map.sourcesContent = [ source ]

some time after the compilation, as far as I can tell from a minimal project.

**Comment by dummdidumm** [comment]
This sounds like https://github.com/ampproject/remapping/issues/116 , which is used in Svelte core to merge the preprocessed source map and the resulting map. If the preprocessed source map is empty, it happens.

**Comment by non25** [comment]
Should we fix it in `svelte-loader` with `js.map.sourcesContent = [ source ]`?
Or it should be fixed upstream?

**Comment by dummdidumm** [comment]
There is a draf PR for it upstream in Svelte core https://github.com/sveltejs/svelte/pull/6089 . Does the current behavior cause problems or is it just a "I noticed this" thing?

**Comment by rtpt-jonaslieb** [comment]
For my use case, this means that I always need to jump back to the editor to see the actual Svelte code. Ideally, I'd have all of that directly in the browser...
