### ISSUE TITLE
Source maps seems to break after version 3.1.0

### ISSUE THREAD

**Issue by raythurnevoid** [sveltejs/svelte-loader#176]
### 3.1.0
![image](https://user-images.githubusercontent.com/53383860/114327753-9a0ec600-9b3a-11eb-8b9c-79e4b6001af5.png)

### 3.0.0 rollback
![image](https://user-images.githubusercontent.com/53383860/114327769-ab57d280-9b3a-11eb-9fb0-1876df6de487.png)

You can check this behavior here: https://github.com/raythurnevoid/svelte-template/tree/svelte-loader-3.1.0
Source maps work for ts files but not for svelte.

Env;
- webpack: ^5.31.2
- webpack-dev-server: ^3.11.2
- typescript: ^4.2.4
- svelte: ^3.37.0
- OS: Windows 10
- Node: 14.16.1 (LTS)

**Comment by non25** [comment]
This is where things started: https://github.com/sveltejs/svelte-loader/issues/171

Currently I don't understand where issue should be fixed. In svelte core or in `svelte-loader`.

Here's PR for upstream: https://github.com/sveltejs/svelte/pull/6089

We can fix this as proposed by @rtpt-jonaslieb, but I have no idea how this will impact future svelte versions.

@dummdidumm Thoughts?

**Comment by dummdidumm** [comment]
Mhm the upstream PR should only take effect in situations when there's no script tag, but in this case one exists.

**Comment by non25** [comment]
Can't make things inconvinient in Firefox, tried to throw an error from svelte component.
Jumped to bundled code in console, from there jumped to the original location - component source. Source is there. The line in question is highlighted.

@raythurnevoid Can you try this branch and report if that fixes things for you?

```sh
npm i -D non25/svelte-loader#fix-sources-content
# or in yarn
yarn add -D svelte-loader@non25/svelte-loader#fix-sources-content
```

**Comment by raythurnevoid** [comment]
@non25 Works like a charms!
![image](https://user-images.githubusercontent.com/53383860/114643723-839d7180-9cd6-11eb-9a0f-96bf06e84a0d.png)

You are amazing!
