### ISSUE TITLE
`shared` should be resolved

### ISSUE THREAD

**Issue by Rich-Harris** [sveltejs/svelte-loader#19]
rollup-plugin-svelte [resolves the shared helpers path relative to the plugin itself](https://github.com/rollup/rollup-plugin-svelte/blob/master/src/index.js#L38). that doesn't happen here, and it seems maybe that's resulting in [incorrect behaviour](https://gitter.im/sveltejs/svelte?at=58d323016d7eb18404f79de9) somehow?

**Comment by nikku** [comment]
Related, but not sure if it is the issue: We should probably keep [this test](https://github.com/sveltejs/svelte-loader/commit/b10c59a76d0ddbf0783b6217614e35e05747a9d4#diff-b5046ba21d182ea7df467bd67a2cbe7dL188) to verify the correct `shared` inclusion.

**Comment by polandj** [comment]
Webpack output of pre-2.0.0:

Hash: edabde4e222b7cfed336
Version: webpack 2.2.1
Time: 335ms
     Asset    Size  Chunks                    Chunk Names
    app.js  286 kB       0  [emitted]  [big]  app
app.js.map  361 kB       0  [emitted]         app
   [0] ./main.svl 10.5 kB {0} [built]
   [2] /Users/jp/Documents/Arduino/chickencoop/~/jquery/dist/jquery.js 268 kB {0} [built]
    + 1 hidden modules

And post 2.0.0

Hash: c573832bee81959784e5
Version: webpack 2.3.1
Time: 1214ms
     Asset    Size  Chunks                    Chunk Names
    app.js  299 kB       0  [emitted]  [big]  app
app.js.map  368 kB       0  [emitted]         app
   [0] ./main.svl 8.43 kB {0} [built]
   [1] /Users/jp/Documents/Arduino/chickencoop/~/jquery/dist/jquery.js 268 kB {0} [built]
   [2] /Users/jp/Documents/Arduino/chickencoop/~/svelte/shared.js 5.4 kB {0} [built]
   [3] ./app.js 101 bytes {0} [built]

I was mainly just surprised.  The code only has one component thus far, so I imagine pulling out shared is actually a loss in this case, but a win once you have multiple components.
