### ISSUE TITLE
Svelte dependency old version

### ISSUE THREAD

**Issue by neoel** [sveltejs/svelte-loader#21]
I've tried to build a project using this loader, but it didn't compile properly. It is compiling with svelte 1.6.0.

Not sure why svelte is defined as dependency and peerDependency. But it's not taking the peerDep.

**Comment by Rich-Harris** [comment]
It's defined as a `devDependency`, for the sake of testing — `npm install -D svelte-loader` shouldn't install Svelte along with it, you have to do `npm i -D svelte` separately with this loader. Not sure where your old version is coming from? The latest (1.13.1) satisifies the semver range specified in `peerDependencies`.
