### ISSUE TITLE
Doesn't catch ts errors and builds 

### ISSUE THREAD

**Issue by pociej** [sveltejs/svelte-loader#211]
In my svelte component I use typescript. If component is bug free everything is ok, but it also builds properly when there is typescript error ( VSC properly highlights errors but webpack seems to ignore them and builds). This touches only the .svelte files. .ts files are properly handled so I guess fault is somewhere in this loader.

**Comment by dummdidumm** [comment]
The loader is not concerned with type-checking. Use [`svelte-check`](https://www.npmjs.com/package/svelte-check) for this.
