### ISSUE TITLE
options.css as a boolean is deprecated. Use 'injected' instead of true.

### ISSUE THREAD

**Issue by benperiton** [sveltejs/svelte-loader#216]
After upgrading svelte to 3.53.0 I get a load of warnings about options.css

Looks like this hasn't been updated to match the 'injected' instead of true?

https://github.com/sveltejs/svelte-loader/blob/bba9acb99c76a81072f9ae75a5a78b8b518dc451/index.js#L31

**Comment by dummdidumm** [comment]
3.53.1 no longer shows this warning, I'm therefore closing this.
