### ISSUE TITLE
Tags don't match the versions published on npm

### ISSUE THREAD

**Issue by the0neWhoKnocks** [sveltejs/svelte-loader#221]
When there aren't changelogs in "Releases" for a project, I go through the `tags` to see what's changed. Currently npm lists latest at `3.1.4`, but your tags only go to `3.1.2`.

**Comment by Conduitry** [comment]
Hm. @dummdidumm I think you'd been publishing the past couple of versions to npm. Have you created Git tags when you did so? Did you just neglect to push them?

**Comment by dummdidumm** [comment]
I forgot, will try to get it up to date
