### ISSUE TITLE
CRLF line endings causes svelte-loader to fail to compile await blocks correctly.

### ISSUE THREAD

**Issue by bryanwood** [sveltejs/svelte-loader#38]
If you have a component `.html` source file that has `CRLF` line endings with an `{{#await}}` block when compiled with `svelte-loader` you will get an error like this:

```
ERROR in ./example.html
Module parse failed: Unexpected token (86:3)
You may need an appropriate loader to handle this file type.
|
  // (2:{{then result}}ing</p>
| function create_pending_block(state, _, component) {
|       var p;
|
 @ ./index.js 1:0-37
```

Error doesn't occur when line endings are switched to `LF`.

I've made a repository with an example:
https://github.com/bryanwood/svelte-crlf-await-block

Can workaround this by using `LF` for line endings.

svelte version: 1.49.3
svelte-loader version: 2.3.2
webpack version: 3.10.0

**Comment by Conduitry** [comment]
Tidying up - this was actually a problem in Svelte itself https://github.com/sveltejs/svelte/issues/1132 and has been fixed since version 1.54 in January
