### ISSUE TITLE
hotReload: true prevents page navigation

### ISSUE THREAD

**Issue by Rich-Harris** [sveltejs/svelte-loader#43]
I haven't looked into this at all yet, but it appears that `hotReload: true` is breaking page navigation in Sapper. My hunch is that it doesn't play nicely with components that have already been destroyed with `component.destroy()`. cc @ekhaled

**Comment by ekhaled** [comment]
destroy is proxied through.. I'm not sure but I'll have a look.
Where's the page navigation code in sapper?

**Comment by ekhaled** [comment]
Think it might be to do with `hydrate` support

**Comment by Rich-Harris** [comment]
That sounds plausible... the navigation code is in https://github.com/sveltejs/sapper/blob/master/src/runtime/index.ts, specifically [this function](https://github.com/sveltejs/sapper/blob/master/src/runtime/index.ts#L47-L76)

**Comment by ekhaled** [comment]
cheers, I'm on it right now, will keep you posted

**Comment by Rich-Harris** [comment]
awesome, thank you

**Comment by ekhaled** [comment]
I might need some help with svelte/sapper internals.

For example (this is from sapper-template), there is a component `routes\index.html`.. it contains `<Layout>`. While `_mount()` is called in `<Layout>`, why is `_mount` never called on `routes/index.html` ?

**Comment by Rich-Harris** [comment]
`_mount` is a semi-private API that a parent uses to control exactly when/where its child components are mounted. `routes/index.html` is a top-level component, so it mounts itself, but `<Layout>` is a child of `routes/index.html`, which means `routes/index.html` is responsible for mounting it using `layout._mount`.

If you go here https://svelte.technology/repl?version=1.55.0&example=nested-components and click the input/output toggle, you'll notice `nested._mount` on line 24, but on line 58 the `App` mounts its own fragment *without* calling `_mount` (though it could be rewritten so that it always did go through `_mount`, now that I think about it)

**Comment by ekhaled** [comment]
Thanks, makes a lot of sense... 
I hijack the `_mount` to do some book keeping.

Is this snippet the self-mounting code?:
```js
if (options.target) {
		if (options.hydrate) throw new Error("options.hydrate only works if the component was compiled with the `hydratable: true` option");
		this._fragment.c();
		this._fragment.m(options.target, options.anchor || null);

		........
}

```

**Comment by ekhaled** [comment]
yeah, sorry.. ignore me.. you pointed out the line number

**Comment by ekhaled** [comment]
just to keep you updated... I have skirted around the self-mounting components issue.
However, it would be better to make them go through `_mount` as you suggested.

Still trying to figure out why `preload()` breaks rendering. Something to do with `data` not getting passed through properly.

**Comment by Rich-Harris** [comment]
Everything seems to be working well with this, the latest Sapper (and https://github.com/sveltejs/sapper-template/pull/40), so I'll close this. Thank you so much!
