### ISSUE TITLE
hotReload does not like bound properties

### ISSUE THREAD

**Issue by aphitiel** [sveltejs/svelte-loader#46]
When hotReload is enabled and component contains a bound property, it sadly throws `TypeError: xxx._bind is not a function.`

Simplest reproduction would be a new [sapper-template](https://github.com/sveltejs/sapper-template), and  adding e.g. `bind:value` to the `<Layout` component in routes/index.html:
`<Layout bind:value page='home'>`

**Comment by Rich-Harris** [comment]
I've found this too. I guess it's because the proxy doesn't know about _bind? @ekhaled does this ring a bell?

**Comment by ekhaled** [comment]
Yeah, I somehow missed _bind. Thankfully @aphitiel has submitted a PR which we are in the process of finalising

**Comment by ekhaled** [comment]
Right, thanks to @aphitiel this can be now closed.
I don't know whether you would need to cut another release. I have released `v1.1.5`, but package.json here says `"svelte-dev-helper": "^1.1.4",` so should be fine I'm guessing.

**Comment by Rich-Harris** [comment]
looks like we can close this — working for me with a fresh install 🎉
