### ISSUE TITLE
Cannot set property '_observers' of undefined

### ISSUE THREAD

**Issue by andyjessop** [sveltejs/svelte-loader#47]
I've installed the `svelte-loader` package and have added the following configuration:

```
     {
        test: /\.(html|svelte)$/,
        exclude: /node_modules/,
        use: {
          loader: 'svelte-loader',
          options: {
            emitCss: true,
            hotReload: true,
          },
        },
      },
```
When running webpack I get the following error:
`Template execution failed: TypeError: Cannot set property '_observers' of undefined`

Without the `html` test option, this works fine, but I'd like to use the `.html` extension in my project. Is there anything else I need to do to get it working?

**Comment by ekhaled** [comment]
This might be HMR related, can you check if you get the same error with `hotReload : false`

**Comment by andyjessop** [comment]
I've tried it with that setting and I still get the same error.

**Comment by Rich-Harris** [comment]
This is odd — if you're still getting this, any way you can create a minimal repro? Thanks
