### ISSUE TITLE
hotReload: true breaks styles with emitCss

### ISSUE THREAD

**Issue by Rich-Harris** [sveltejs/svelte-loader#61]
Changing the contents of a `<style>` block causes the existing styles for that component to be removed. Something to do with the hash no longer matching.

Without `emitCss`, it works as expected, so a possible workaround is to only use `emitCss` in production. Far from ideal though.

**Comment by kaisermann** [comment]
After some research, I've found that `mini-css-extract` doesn't support HMR yet. The readme [`suggests`](https://github.com/webpack-contrib/mini-css-extract-plugin#advanced-configuration-example)to use `style-loader` for development builds that should support HMR.

**Comment by Rich-Harris** [comment]
Closing this now that that PR has been merged. Thanks!
