### ISSUE TITLE
Emit JS?

### ISSUE THREAD

**Issue by kaisermann** [sveltejs/svelte-loader#62]
I'm currently making a `svelte-webpack-template` for a somewhat old webkit environment. With `babel-preset-env`, I'm trying to automatically polyfill my project's and svelte's generated code. 

My first attempt was to call `babel-loader` after `svelte-loader` was done:

![image](https://user-images.githubusercontent.com/12702016/39606378-8287c096-4f0b-11e8-9bf2-4d66474b83c1.png)

Unfortunately, it stopped working with the last updates of `svelte-loader`/`svelte` and now `babel-loader` tries to read the template file itself ( ¯\\\_(◕_◕)\_\/¯ ).  

My next thought was probably a dumb question, but... would it make sense to "emit" the `js` generated by the `svelte` compiler? 

(or maybe there's a better way to do this...)

**Comment by Rich-Harris** [comment]
eek! I honestly have no idea. Hopefully someone else will...

**Comment by kaisermann** [comment]
I was able to make it polyfill the `svelte/shared.js` again by enforcing my `.babelrc.js` to `babel-loader`. It wasn't parsing the `shared.js` because it's looking for a babel config inside the `node_modules/svelte` directory.

If anyone is on the same boat as I was, this will make the `babel-loader` catch the `import {...} from 'svelte/shared.js'` from compiled templates:

```js 
// partial webpack.config.js
const babelrc = require('./.babelrc.js')
delete babelrc.sourceMaps
...
{
    loader: 'babel-loader',
    options: {
      babelrc: false,
      ...babelrc,
    },
},
```

I'm gonna close this since I've already solved my main issue.

**PS:** regarding https://github.com/sveltejs/svelte/pull/1359, if the output of `svelte/compiler` will be ES6 code, how would we handle ES5-only browsers?

**Comment by roemhildtg** [comment]
Wait, I might be running into this too. I'm trying to get babel to transpile the svelte code into IE11 friendly versions and the shared.js file still has arrow functions in it. I'm not really following what you're doing there, can you tell me how to fix this?

```
{
            test: /\.svelte$/,
            use: [{
                loader: 'babel-loader',
                options: {
                    cacheDirectory: true,
                    sourceMap: true,
                },
            }, {
                loader: 'svelte-loader',
                options: {
                    emitCss: true,
                },
            }],
        },
```

**Comment by martynchamberlin** [comment]
@kaisermann Thanks a million for posting this code. I had the exact same problem and your code screenshot was the key. I needed to do the babel-loader in a `use` array, instead of just having a `loader` property on the rule.

@roemhildtg I think you're on the right track, you just need to make sure you're also testing for `.js` files and running the `babel-loader` on them too.

**Comment by martynchamberlin** [comment]
@roemhildtg To follow up on this, because I was having the same issue too just now. Since the `shared.js` file is coming from `node_modules/svelte`, you'll probably need to make sure your Babel is transpiling that directory. We almost always in our babel config exclude the `node_modules` wholesale, which is why it isn't picking up that `shared.js` file.

**Comment by borracciaBlu** [comment]
**Case => function error not transpiled IE11**

       // WRONG
       // missing /node_modules\/(?!svelte)/ for js file
       // thus can not pick up node_modules/svelte/shared.js
       {
           test: /\.js$/,
           loader: 'babel-loader',
           exclude: /node_modules/,
       },
       {
           test: /\.svelte/,
           exclude: /node_modules\/(?!svelte)/,
           use: [loaders.babel, loaders.svelte],
       },

       // CORRECT
       {
           test: /\.js$/,
           loader: 'babel-loader',
           exclude: /node_modules\/(?!svelte)/,,
       },
       {
           test: /\.svelte/,
           exclude: /node_modules\/(?!svelte)/,
           use: [loaders.babel, loaders.svelte],
       },
