### ISSUE TITLE
Publish v1.1.0

### ISSUE THREAD

**Issue by nikku** [sveltejs/svelte-loader#7]
I already updated the `CHANGELOG` and bumped the dependency (https://github.com/sveltejs/svelte-loader/commit/cdd1251b9d889eb0fba0a8a143f71f84d4d8e9c3).

Don't have the permissions to publish `svelte-loader` on NPM though.

**Comment by Rich-Harris** [comment]
Done – thanks. Have added you as a package owner on npm
