### ISSUE TITLE
Class based components

### ISSUE THREAD

**Issue by Stormsher** [sveltejs/svelte-loader#71]
I prefer to use separate structure for html/css/js rather than single file. Are there any ways to deal with that using svelte-loader? Or another solutions for this problem?

**Comment by Gotterbild** [comment]
Have you tried `<script src="path/to/your/js"></script>`?

I believe with styles you can use `@import`.

**Comment by kaisermann** [comment]
You should use a custom preprocessor for importing external files. For example, there's [`svelte-preprocess`](https://github.com/kaisermann/svelte-preprocess).

**Comment by Conduitry** [comment]
Using a preprocessor is the right way to go about this, regardless of bundler.
