### ISSUE TITLE
Specify that svelte compiler options can be specified in loader options

### ISSUE THREAD

**Issue by AleksandrSl** [sveltejs/svelte-loader#76]
It's not obvious that compiler options such as `customElement` and `shared` can be specified in loader options. Maybe it's worth mentioning in README

**Comment by UziTech** [comment]
Wow! I have been trying to export a customElement for longer than I care to admit. If I knew all I had to do is add `customElement: true` to the svelte-loader options it would have saved me lots of time.

**Comment by benmccann** [comment]
The options were moved under `compilerOptions` in `master`. I agree it'd be good to add to the README. I'll review and merge a PR if anyone wants to send one
