### ISSUE TITLE
onMount failing

### ISSUE THREAD

**Issue by syfgkjasdkn** [sveltejs/svelte-loader#84]
👋

To reproduce: https://github.com/syfgkjasdkn/onMount-trouble

### The problem

When I add [`onMount(...)`](https://github.com/syfgkjasdkn/onMount-trouble/blob/6025aee7b99b18aedcfb278c0295c6433d3c9205/src/App.svelte#L5-L7) to a component which is loaded with `svelte-loader`, the app fails at runtime with the following error:

```
Uncaught TypeError: Object(...) is not a function
    at instance (App.svelte:70)
    at init (internal.js:1374)
    at new App (App.svelte:85)
    at eval (main.js:4)
    at Module../src/main.js (app.js:133)
    at __webpack_require__ (app.js:20)
    at eval (main.js:1)
    at Object.0 (app.js:144)
    at __webpack_require__ (app.js:20)
    at app.js:84
```

The "offending" part (App.svelte:70) is:

```js
Object(svelte__WEBPACK_IMPORTED_MODULE_1__["onMount"])(() => { // x error happens here
  console.log("mounted");
});
```

**Comment by syfgkjasdkn** [comment]
When `onMount(...)` is commented out, the app works fine.

**Comment by syfgkjasdkn** [comment]
Strange ... Just tried [sveltejs/template-webpack](https://github.com/sveltejs/template-webpack) and it works fine with `onMount` there: https://github.com/syfgkjasdkn/onMount-no-trouble

**Comment by jikkai** [comment]
I have the same problem.

Try this

```diff
  resolve: {
-    extensions: [".js", ".svelte"]
+    extensions: [".mjs", ".js", ".svelte"]
  }
```
