### ISSUE TITLE
File names can only contain /a-zA-Z_$0-9/ so '图片.svelte' is not permitted

### ISSUE THREAD

**Issue by lunchboxer** [sveltejs/svelte-loader#86]
using characters other than alphanumeric plus _ or $ in file names of sapper routes gives the following error.

```
ERROR in ./src/routes/你好.svelte
Module build failed (from ./node_modules/svelte-loader/index.js):
Error: TypeError: TypeError: Cannot read property 'toUpperCase' of undefined
    at /home/james/www/sapper-v3-webpack/node_modules/svelte-loader/index.js:200:16
 @ ./src/node_modules/@sapper/internal/manifest-client.mjs 30:12-86
 @ ./src/node_modules/@sapper/app.mjs
 @ ./src/client.js
> Encountered errors while building app
```

It looks like the sanitize function at line 137 converted my filename to an empty string before trying to capitalize it. Seems to me like more character sets should be allowed.

also https://github.com/lovell/limax was mentioned in the chat

**Comment by mindrones** [comment]
We're moving to https://www.npmjs.com/package/@sindresorhus/slugify as `limax` has dependencies depending on native modules which will require you to use `node-gyp`, which in turns depends on python, make, gcc, and it can create problems to those not having a development env on the machine in use.

This could be useful instead: https://github.com/sindresorhus/filenamify
