### ISSUE TITLE
Postcss-preset-env && emit css

### ISSUE THREAD

**Issue by frank3stein** [sveltejs/svelte-loader#91]
While using nested css properties of postcss-preset-env, the compiler throws error, although the setting is to emit css. 

As far as I understand the problem, svelte-loader should allow the other loaders to handle the css if the emitCss is **true**. Otherwise it does not allow the other loaders to do their job and stops the compilation all together. I guess if implemented, this would also allow you to write SCSS, Less in the style element too inside svelte component.

Only workaround for now is to include separate css file for the svelte component and import it in the script tag of the component. 

The error thrown when nested are used;

Module build failed (from ./node_modules/svelte-loader/index.js):
Error: ParseError: Identifier is expected (16:4)
14:   ul.column {
15:     flex-direction: column;
16:     & li {
        ^
17:       color: black;
18:     }
    at /home/emil/development/cv-to-pdf/node_modules/svelte-loader/index.js:180:12
 @ ./src/App.svelte 15:0-47 22:18-24
 @ ./src/index.js

Here is the webpack settings;
```js
{
        test: /\.(html|svelte)$/,
        exclude: /node_modules/,
        use: {
          loader: "svelte-loader",
          options: {
            emitCss: true,
            hotReload: true
          }
        }
      },
      {
        test: /\.css$/,
        use: ExtractTextPlugin.extract({
          fallback: [{ loader: "style-loader", options: { sourceMap: true } }],
          use: [
            { loader: "css-loader", options: { sourceMap: true } },
            {
              loader: "postcss-loader",
              options: {
                sourceMap: true,
                ident: "postcss",
                plugins: loader => [
                  require("postcss-import")({}),
                  require("postcss-preset-env")(),
                  require("cssnano")()
                ]
              }
            }
          ]
        })
      }
```

**Comment by kaisermann** [comment]
Svelte parses your css between the `style` tags, so it needs to be able to understand what you type there. You need to setup your `preprocess` step: https://svelte.dev/docs#svelte_preprocess for it to understand `postcss`

**Comment by frank3stein** [comment]
One thing I did not understand in svelte-preprocess options in the transformers object
```js
    /**
     * Post process css with PostCSS by defining 'transformers.postcss'
     * Pass 'true' to activate PostCSS transforms and use the `postcss.config.js`
     */
    postcss: true,
    postcss: {
      plugins: [
        require('autoprefixer')({ browsers: 'last 2 versions' })
      ]
    },
```
Two properties named postcss, how does that work ? It runs in webpack when it is like this. I don't understand why. 

Thanks for the link and writing the package. I ended up using svelte-preprocess. Here is my setup incase anyone is wondering a working setup. 

```js
{
        test: /\.(html|svelte)$/,
        exclude: /node_modules/,
        use: {
          loader: "svelte-loader",
          options: {
            emitCss: true,
            hotReload: true,
            preprocess: require("svelte-preprocess")({
              transformers: {
                // postcss: true,
                postcss: {
                  plugins: [
                    require("postcss-import")({}),
                    require("postcss-preset-env")({
                      // stage: 0,
                      features: { "nesting-rules": true },
                      browsers: "last 10 versions"
                    }),
                    require("cssnano")()
                  ]
                }
              }
            })
          }
        }
      },
      {
        test: /\.css$/,
        use: ExtractTextPlugin.extract({
          fallback: [{ loader: "style-loader", options: { sourceMap: true } }],
          use: [
            { loader: "css-loader", options: { sourceMap: true } }
          ]
        })
      }
```

**Comment by kaisermann** [comment]
@frank3stein The two properties are just separate examples of possible configurations! Sorry for the confusion, my bad heh.

In case you want to reuse your postcss configuration, I'd recommend you to create a `postcss.config.js` file and just pass the `postcss: true` ;)

If your problem is solved, be free to close the issue 😁

**Comment by frank3stein** [comment]
Yes, I got it after reading it a couple of times. But the interesting part is when included in webpack config like that, it still runs without any errors. Thanks again.
