### ISSUE TITLE
Per component compiler options

### ISSUE THREAD

**Issue by glinesbdev** [sveltejs/svelte-loader#93]
Similar to #76 but extended.

While configuring Svelte via Webpack using svelte-loader, I see that you can set compiler options. The option that I am most interested in is `customElement`. It seems that you can either have Svelte compile down to only custom elements or only Svelte class objects, but not both.

In trying to configure only one component, I came across `<svelte:options>` which you can specify the `tag` name of the custom element. Is there a way to selectively compile a Svelte component to a custom element in an "opt-in" style like `<svelte:options>`?

**Comment by 0gust1** [comment]
imho it's more a webpack question. 

You could write a function in your webpack config that contextually feed options to the loader.  
You could also for example split your webpack base config across several files and require the wanted options from there (it would be useful for "per set of components" options).
